apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - image: davidbour/authapp:f940da23e39490fda9fbc268c53adb5f0bbb991f
          name: my-api
          ports:
            - containerPort: 8000
