apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - image: davidbour/authapp:647ba559a732e74f85eeed829736bcfc239714d8
          name: my-api
          ports:
            - containerPort: 8000
