version: "3.9"

services:
  # keycloak:
  #   container_name: keycloak
  #   command: ["start", "--optimized"]
  #   environment:
  #     - KEYCLOAK_ADMIN=keycloak
  #     - KEYCLOAK_ADMIN_PASSWORD=keycloak
  #     - KC_HOSTNAME=keycloak
  #     - KC_DB_PASSWORD=keycloak
  #     - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
  #     - KC_DB_USERNAME=keycloak
  #   build:
  #     context: ./keycloak
  #     args:
  #       - KC_CACHE_STACK=udp
  #   ports:
  #     - 8443:8443
  #   networks:
  #     - backend
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  api:
    container_name: api
    build: ./api
    ports:
      - 8000:8000
    networks:
      - backend

  # mysql:
  #   container_name: mysql
  #   image: mysql:8
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=keycloak
  #     - MYSQL_DATABASE=keycloak
  #     - MYSQL_USER=keycloak
  #     - MYSQL_PASSWORD=keycloak
  #   ports:
  #   - 3306:3306
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s
  #   networks:
  #     - backend

networks:
  backend: