version: "3.9"

services:
  # keycloak:
  #   container_name: keycloak
  #   command: ["start", "--optimized"]
  #   environment:
  #     - KEYCLOAK_ADMIN=keycloak
  #     - KEYCLOAK_ADMIN_PASSWORD=keycloak
  #     - KC_HOSTNAME=keycloak
  #     - KC_DB_PASSWORD=keycloak
  #     - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
  #     - KC_DB_USERNAME=keycloak
  #   build:
  #     context: ./keycloak
  #     args:
  #       - KC_CACHE_STACK=udp
  #   ports:
  #     - 8443:8443
  #   networks:
  #     - backend
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  otel:
    container_name: otel
    command:
      - sh
      - -c
      - "opentelemetry-instrument flask run --host=0.0.0.0"
    build: ./intro-to-instrumentation
    ports:
      - 5001:5000
    environment:
      - OTEL_SERVICE_NAME=otel-example
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    networks:
      - backend

  api:
    container_name: api
    command: 
    - sh
    - -c
    - opentelemetry-instrument uvicorn main:app --host=0.0.0.0
    build: ./api
    ports:
      - 8000:8000
    networks:
      - backend
    environment:
      - OTEL_SERVICE_NAME=api
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - jaeger

  logger:
    container_name: logger
    build: ./logger
    ports:
      - 9000:9000
    environment:
      - OTEL_SERVICE_NAME=logger
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    command:
    - sh
    - -c
    - "opentelemetry-instrument flask run --host=0.0.0.0 --port=9000"
    networks:
      - backend
    depends_on:
      - jaeger

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.42
    ports:
      - 6831:6831
      - 6832:6832
      - 5778:5578
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - backend

  # mysql:
  #   container_name: mysql
  #   image: mysql:8
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=keycloak
  #     - MYSQL_DATABASE=keycloak
  #     - MYSQL_USER=keycloak
  #     - MYSQL_PASSWORD=keycloak
  #   ports:
  #   - 3306:3306
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s
  #   networks:
  #     - backend

networks:
  backend: