apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{namespace}}-api'
    spec:
      project: default
      source:
        repoURL: https://github.com/david-bour/gitoops.git
        targetRevision: HEAD
        path: infrastructure/deployments/environments/{{namespace}}
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'