init:
	source venv/bin/activate && \
	pip install -v "opentelemetry-api==1.18.0" && \
	pip install -v "opentelemetry-sdk==1.18.0" && \
	pip install -v "opentelemetry-exporter-otlp==1.18.0" && \
	pip install -v "opentelemetry-distro==0.39b0"