name: Build Dockerfile
on: [push]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: davidbour/authapp:${{ github.sha }},davidbour/authapp:latest
          context: ./api

      - name: Update Image Tag in Dev
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'infrastructure/deployments/environments/dev/deployment.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: 'davidbour/authapp:${{ github.sha }}'
          branch: main
          createPR: false
          targetBranch: main
          masterBranchName: main
          message: "Update image to tag ${{ github.sha }}"
          commitChange: true

      - name: Debug
        run: cat 'deployment.yaml'
        working-directory: ./infrastructure/deployments/environments/dev